add solution
mate-academy/py-car-wash-station pull request #1229
Opened 2024-04-25 10:08 UTC by midetc

2024-04-25 10:24 UTC, ArsenPidhoretskyi requested changes

2024-04-25 10:24 UTC, ArsenPidhoretskyi commented on app/main.py
> +        if cars_can_wash:
This condition is redundant

2024-04-25 10:24 UTC, ArsenPidhoretskyi commented on app/main.py
> +        car.clean_mark = self.clean_power
wash_single_car - method, that washes a single car, so it should have clean_mark equals wash station's clean_power, if wash_station.clean_power is greater than car.clean_mark

Condition is skipped

2024-04-25 11:56 UTC, vasylhnatiuk requested changes

2024-04-25 11:56 UTC, vasylhnatiuk commented on app/main.py
> +        car.clean_mark = self.clean_power
add condition here as well

2024-04-26 09:06 UTC, ArsenPidhoretskyi approved these changes
Good job!

2024-04-26 09:06 UTC, closed without merging