Solution
mate-academy/py-car-wash-station pull request #1330
Opened 2024-06-17 14:39 UTC by KostiantinPastukh

2024-06-17 16:14 UTC, Dimosphen1 requested changes
Several changes were requested

2024-06-17 16:14 UTC, Dimosphen1 commented on app/main.py
> +                 brand: str) -> None:
Place each argument including `self` on a new line so that there would be no arguments on the same line with opening and closing parenthesis. It will help to improve the code style and readability. Apply this change for the `CarWashStation` class as well

2024-06-17 16:14 UTC, Dimosphen1 commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
Indicate a list of what instances you expect to obtain for `cars` in the type annotation

2024-06-17 16:14 UTC, Dimosphen1 commented on app/main.py
> +            1)
In case there are no arguments on the same line with an opening parenthesis, your closing parenthesis should not have any arguments on the same line as well. Please, resolve this issue

2024-06-18 11:38 UTC, KostiantinPastukh commented
Чому не прийнято завдвння?

2024-06-18 13:04 UTC, KostiantinPastukh commented on app/main.py
> +                 brand: str) -> None:
Я ж в останньому Solution наче виправив це.

2024-06-26 14:45 UTC, closed without merging