Task 5
mate-academy/py-car-wash-station pull request #1411
Opened 2024-07-23 15:25 UTC by Poznanskyi

2024-07-24 05:54 UTC, Oleksl888 requested changes

2024-07-24 05:54 UTC, Oleksl888 commented on app/main.py
> +    def __init__(self, comfort_class: int, clean_mark: int, brand: str)\
When you have multiple params it is a best practice to have each parameter on new line. Also we don't use `\` for line breakers as per styling guidelines

2024-07-24 05:54 UTC, Oleksl888 commented on app/main.py
> +        self, distance_from_city_center: float, clean_power: int,
Same as above - each param must be on separate line

2024-07-24 05:54 UTC, Oleksl888 commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
Can you specify data type for list contents?

2024-07-24 05:54 UTC, Oleksl888 commented on app/main.py
> +        cost = (
No need to store result of calculation in variable since you are not going to reuse it.

2024-07-24 05:54 UTC, Oleksl888 commented on app/main.py
> +        self.average_rating = round(
Same as above - you can rewrite this formula so you don't have to create total_rating variable

2024-07-25 02:55 UTC, MNDonut requested changes

2024-07-25 02:55 UTC, MNDonut commented on app/main.py
> +                 brand: str) -> None:
The best approach is to move these parameters on the next lines after function name

2024-07-25 02:55 UTC, MNDonut commented on app/main.py
> +        self.brand = brand
Note that some parameters can accept only specific values

2024-07-25 02:55 UTC, MNDonut commented on app/main.py
> +        self.count_of_ratings = count_of_ratings
Note that some parameters can accept only specific values

2024-07-25 02:55 UTC, MNDonut commented on app/main.py
> +                 count_of_ratings: int) -> None:
The best approach is to move these parameters on the next lines after function name

2024-07-25 11:31 UTC, MNDonut requested changes

2024-07-25 11:31 UTC, MNDonut commented on app/main.py
> +            raise ValueError("Must be between 0.0 and 5.0")
let's follow the same approach everywhere. Either double comparison or range

2024-07-25 13:43 UTC, MNDonut requested changes

2024-07-25 13:43 UTC, MNDonut commented on app/main.py
> +        if not (0.0 <= average_rating <= 5.0):
still not fixed. you use here double comparison, but for other ifs use range

2024-07-25 13:43 UTC, MNDonut commented on app/main.py
> +        if not (0.0 <= new_rating <= 5.0):
the same here

2024-07-25 19:16 UTC, LiudmylaKulinchenko approved these changes
Good job 👏

2025-02-18 20:43 UTC, closed without merging