Solution
mate-academy/py-car-wash-station pull request #1485
Opened 2024-09-06 18:59 UTC by Viacheslav417865

2024-09-06 20:04 UTC, vsmutok requested changes

2024-09-06 20:04 UTC, vsmutok commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
```suggestion
    def serve_cars(self, cars: list[Car]=) -> float:
```

2024-09-06 20:04 UTC, vsmutok commented on app/main.py
> +                self.wash_single_car(car)  # викликаємо метод wash_single_car
please remove this comment

2024-09-07 09:42 UTC, Viacheslav417865 commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
If i "Suggested change"  # def serve_cars(self, cars: list[Car]=) -> float: SyntaxError: expected default value expression

2024-09-07 09:59 UTC, closed without merging