Solution
mate-academy/py-car-wash-station pull request #1544
Opened 2024-09-30 13:41 UTC by SerhiiK05

2024-09-30 15:09 UTC, sumseer requested changes

2024-09-30 15:09 UTC, sumseer commented on app/main.py
> +        price = (
Fix flake8 error

price = (
            car.comfort_class
            * (self.clean_power - car.clean_mark)
            * self.average_rating
        ) / self.distance_from_city_center

2024-09-30 15:53 UTC, sumseer approved these changes
GJ!

2024-09-30 16:14 UTC, Y-Havryliv requested changes

2024-09-30 16:14 UTC, Y-Havryliv commented on app/main.py
> +                total_income += wash_cost
```suggestion
                total_income += self.calculate_washing_price(car)
```
this would be better, and you don't need this redundant variable

2024-10-02 07:01 UTC, AnyoneClown requested changes

2024-10-02 07:01 UTC, AnyoneClown commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
Add more descriptive type hint for `cars`

2024-10-02 07:01 UTC, AnyoneClown commented on app/main.py
> +        total_ratings += new_rating
You can do this in 1 line

2024-10-02 07:23 UTC, AnyoneClown approved these changes
Good, but don't forget to fix last comment

2025-06-04 12:17 UTC, closed without merging