Solution
mate-academy/py-car-wash-station pull request #239
Opened 2022-10-06 16:45 UTC by bythewaters

2022-10-07 06:58 UTC, Abnormaltype requested changes

2022-10-07 06:58 UTC, Abnormaltype commented on app/main.py
> +        return car.clean_mark <= self.clean_power
it's not correct

2022-10-07 06:58 UTC, Abnormaltype commented on app/main.py
> +                car.clean_mark = self.clean_power
you should do this in wash_single_car

2022-10-10 09:49 UTC, IvanRamyk approved these changes
Good job!

2022-10-10 09:51 UTC, IvanRamyk approved these changes

2024-06-10 16:56 UTC, closed without merging