car_washing_station v1
mate-academy/py-car-wash-station pull request #26
Opened 2022-05-03 11:17 UTC by SairusQw

2022-05-11 07:55 UTC, IvanRamyk requested changes

2022-05-11 07:55 UTC, IvanRamyk commented on app/main.py
> +        full_rating = self.average_rating * (self.count_of_ratings - 1)
If you swap the first two lines of the method It'll become more readable :) In that case, you shouldn't subtract one from the rating count.
```suggestion
        full_rating = self.average_rating * self.count_of_ratings
```

2022-05-19 06:41 UTC, Abnormaltype requested changes
All tests should are passed

2022-06-06 11:39 UTC, IvanRamyk approved these changes
Good job!

2025-03-19 20:18 UTC, closed without merging