Solution
mate-academy/py-car-wash-station pull request #342
Opened 2023-01-12 14:38 UTC by anastasiiashchoholieva

2023-01-13 13:13 UTC, YuriiKindrat requested changes
All tests should pass

2023-01-17 11:59 UTC, andrewbelo requested changes

2023-01-17 11:59 UTC, andrewbelo commented on app/main.py
> +        new_rating = round(((self.average_rating * self.count_of_ratings)
Зайва проміжна змінна і дуже важко дужчи читати, порознось їх на нові рядки, щоб зрозуміліше було

2023-01-17 11:59 UTC, andrewbelo commented on app/main.py
> +                            + rate) / (self.count_of_ratings + 1), 1)
```suggestion
        new_rating = round(
           (self.average_rating * self.count_of_ratings + rate)
           / (self.count_of_ratings + 1),
           1
        )
```
якось так

2023-01-17 11:59 UTC, andrewbelo commented on app/main.py
> +                            + rate) / (self.count_of_ratings + 1), 1)
Краще більше рядків, ніж зосередження ((( ))0))00), його дуже довго потім розбирати, що куди

2023-01-17 11:59 UTC, andrewbelo commented on app/main.py
> +                      * self.average_rating / self.distance_from_city_center, 1)
Те саме можна і тут зробити

2023-01-17 12:38 UTC, andrewbelo approved these changes

2023-02-08 10:40 UTC, closed without merging