Finish Washing Station project
mate-academy/py-car-wash-station pull request #546
Opened 2023-05-13 17:20 UTC by XOctOpus1

2023-05-13 17:45 UTC, Vasyl-Smutok requested changes
Also use `black` to fix indentation

2023-05-13 17:45 UTC, Vasyl-Smutok commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
```suggestion
    def serve_cars(self, cars: list[Car]) -> float:
```

2023-05-13 17:50 UTC, XOctOpus1 commented on app/main.py
> +    def serve_cars(self, cars: list) -> float:
А що таке black?
просто такого ще не було в темах, а flake8 скаржився

2023-05-14 09:13 UTC, vasylhnatiuk approved these changes

2024-11-11 13:27 UTC, closed without merging