Solution
mate-academy/py-car-wash-station pull request #66
Opened 2022-05-25 13:30 UTC by LaskoA

2022-05-25 14:48 UTC, IvanRamyk requested changes
Tests are failed :(

2022-05-25 16:12 UTC, LaskoA commented
please check now after Flake8 fixes, thank you.

2022-05-25 16:21 UTC, IvanRamyk requested changes

2022-05-25 16:21 UTC, IvanRamyk commented on app/main.py
> +        else:
Redundant else branch) 
You don't change anything here

2022-05-26 07:02 UTC, IvanRamyk requested changes
The last thing

2022-05-26 07:02 UTC, IvanRamyk commented on app/main.py
> +    def rate_service(self, r):
Please, choose a more descriptive name than `r`

2022-05-26 12:50 UTC, LaskoA commented
Please check, thank you.

2022-05-27 05:42 UTC, closed without merging