it doesn't work, i need a help
mate-academy/py-car-wash-station pull request #790
Opened 2023-09-28 16:25 UTC by Serhii-Hrynyshyn

2023-09-28 17:16 UTC, EdAlekseiev requested changes
Fix flake8, please. If you need help with it, you can write to chat or attend a Q&A

2023-09-29 08:43 UTC, olena-hul requested changes

2023-09-29 08:43 UTC, olena-hul commented on .flake8
> +[flake8]inline-quotes = "ignore = E203, E266, W503, ANN002, ANN003, ANN101, ANN102, ANN401, N807, N818max-line-length = 79max-complexity = 18select = B,C,E,F,W,T4,B9,ANN,Q0,N8,VNEexclude = venv
I think you should close the PR, and reopen it with the new solution. Make sure flake8 and tests are passing

2023-09-29 08:43 UTC, olena-hul commented on .flake8
> +[flake8]inline-quotes = "ignore = E203, E266, W503, ANN002, ANN003, ANN101, ANN102, ANN401, N807, N818max-line-length = 79max-complexity = 18select = B,C,E,F,W,T4,B9,ANN,Q0,N8,VNEexclude = venv
If you need help, feel free to go to the Q&A

2023-09-29 18:15 UTC, EdAlekseiev requested changes
The file looks broken. Can you close this PR and create a new one? If you need help you can attend the Q&A

2023-09-29 19:14 UTC, closed without merging