Implement py-car-wash-station
mate-academy/py-car-wash-station pull request #811
Opened 2023-10-02 11:15 UTC by SevKrok

2023-10-02 12:13 UTC, vshvanska approved these changes

2023-10-02 16:36 UTC, LiudmylaKulinchenko requested changes

2023-10-02 16:36 UTC, LiudmylaKulinchenko commented on app/main.py
> +            1)
Bad formatting. Better do this:
round(
    ...,
    1
)

2023-10-02 16:36 UTC, LiudmylaKulinchenko commented on app/main.py
> +            1)
fix formatting also here

2023-10-02 16:36 UTC, LiudmylaKulinchenko commented on app/main.py
> +    def wash_single_car(self, car: Car) -> float:
No need to use return here

2023-10-02 17:25 UTC, SevKrok commented on app/main.py
> +    def wash_single_car(self, car: Car) -> float:
But why?
I think this better than use "if" two times and it's contains in one func wash single car

2023-10-02 18:24 UTC, SevKrok commented on app/main.py
> +    def wash_single_car(self, car: Car) -> float:
ok
understood

2023-10-02 19:28 UTC, SelFisher1488 approved these changes
as always the best and cleanest code i've ever seen

2023-10-03 12:01 UTC, LiudmylaKulinchenko requested changes

2023-10-03 12:01 UTC, LiudmylaKulinchenko commented on app/main.py
> +            1)
```suggestion
        return round(
            car.comfort_class * self.average_rating
            * (self.clean_power - car.clean_mark)
            / self.distance_from_city_center, 1
        )
```

fix everywhere

2023-10-03 12:01 UTC, LiudmylaKulinchenko commented on app/main.py
> +            1)
You can find it in the previous task [checklist](https://github.com/mate-academy/py-linter-formatter/blob/master/checklist.md) (at the end of it)

2023-10-03 16:28 UTC, fsocie7y approved these changes
well done 🚀

2023-10-11 09:47 UTC, closed without merging