Solution
mate-academy/py-car-wash-station pull request #817
Opened 2023-10-02 14:43 UTC by YuliaHladyshkevych

2023-10-02 16:46 UTC, skoval7 approved these changes
everything ok

2023-10-02 16:47 UTC, LiudmylaKulinchenko requested changes
All checks have failed

2023-10-03 12:02 UTC, LiudmylaKulinchenko approved these changes
Well done! 😋☀🌼

2023-10-03 12:02 UTC, LiudmylaKulinchenko commented on app/main.py
> +                 clean_mark: int, brand: str) -> None:
You can split each parameter into one line to increase readability

2024-09-20 14:34 UTC, closed without merging