'solution'
mate-academy/py-car-wash-station pull request #856
Opened 2023-10-19 15:46 UTC by xborismenx

2023-10-19 17:59 UTC, EdAlekseiev requested changes
Fix flake8 errors, please

2023-10-21 09:49 UTC, EdAlekseiev requested changes

2023-10-21 09:49 UTC, EdAlekseiev commented on app/main.py
> +    def serve_cars(self, car_list: list) -> float:
You must specify the inner type of list

2023-10-21 09:49 UTC, EdAlekseiev commented on app/main.py
> +    def serve_cars(self, car_list: list) -> float:
```suggestion
    def serve_cars(self, car_list: list[Car]) -> float:
```

2023-10-22 11:42 UTC, ArsenPidhoretskyi requested changes

2023-10-22 11:42 UTC, ArsenPidhoretskyi commented on app/main.py
> +                income += CarWashStation.calculate_washing_price(self, car)
You can call method instead write class name

2023-10-26 08:19 UTC, EdAlekseiev approved these changes
Good job

2026-02-23 08:10 UTC, closed without merging